title: "Kwesi A. Quagraine, Ph.D."
style:
  font-weight: bold
author: "Kwesi Quagraine"
description: "NSF National Center for Atmospheric Research (NSF-NCAR), Boulder, CO" 
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header

# Styling

dark_header: true          # always keep the header dark
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: "About Me"}
  - {file: "research.md", title: "Research interests"}
  - {file: "teaching.md", title: "Teaching"}
  - {file: "publications.md", title: "Publications"}
  - {file: "projects.md", title: "Projects & Grants"}
  - {url: "/Quagraine_KA_CV_Dec2024.pdf", title: "CV"}
  

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Github, icon: github, url: "https://github.com/Akumenyi/"}
  - {title: Twiter, icon: twitter, url: "https://twitter.com/pkdilly"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

remote_theme: niklasbuschmann/contrast@v2.11

plugins:
  - jekyll-remote-theme
  - jekyll-feed
